config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendances
    resources :pictures, only: [:create, :update]
  end
  get 'events/:id/admin/', to: 'events#admin'
  resources :users do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :events
  end

  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  has_one_attached :picture

  # Validations desactivated to test faster
  # in the console


  validates :start_date, presence: true
  validates :duration, presence: true
  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :picture, presence: true
  validates :admin, presence: true

  validates :title, length: { in: 5..240 }
  validates :description, length: { in: 20..1000 }
  validates :price, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :price, numericality: { less_than_or_equal_to: 1000 }
  validates :duration, numericality: { greater_than_or_equal_to: 0 }

  def toggle_review
    self.reviewed = !self.reviewed
  end

  def toggle_validation
    self.validated = !self.validated
  end

  def is_reviewed
    self.reviewed
  end

  def is_validated
    self.validated
  end

  def self.reviewed
    where(reviewed: true)
  end


  private

  def start_date_is_future
    p start_date
    errors.add(:start_date, "is already over") unless :start_date >= 0
  end

  def duration_is_multiple_of_five
    errors.add(:duration, "is not a multiple of 5 (minutes)") unless duration % 5 == 0
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController

  def index
    @events = Event.all.sort_by { |k| k[:start_date] }
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to request.referrer
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :admin]

  def index
    @events = Event.reviewed
  end
  
  def show
    @event = Event.find(params[:id])
    @attendances = Attendance.where(event_id: @event.id)
    @attendants = @attendances.map { |a| User.find(a.user_id) }
  end

  def new
    if user_signed_in?
      flash[:notice] = "Let's go!"
      @event = Event.new
    else
      flash.now[:warning] = "You are not logged in!"
      render
    end
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = "Event bien enregistré ! Bravo, top !"
      redirect_to @event
    else
      flash.now[:warning] = "Ooops, comme un blème.."
      render "new"
    end
  end

  def admin
    @event = Event.find(params[:id])
    if user_signed_in? && @event.user_id != current_user.id
      flash[:warning] = "You're not admin for this event !"
      redirect_back(fallback_location: root_path)
    end
    @attendances = Attendance.where(event_id: @event.id)
    @attendants = @attendances.map { |a| User.find(a.user_id) }
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "Votre event a été mis à jour !"
      redirect_to event_path @event
    else
      flash.now[:error] = "Problème, essayer encore !"
      render :new
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

  def destroy
      @event = Event.find(params[:id])
      @event.destroy
    
      redirect_to events_path
  end

end

private

def event_params
  params.require(:event).permit(:title, :description, :start_date, :price, :location, :duration, :user_id, :picture)
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event.html.erb
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">
        <%= link_to event.title, admin_event_path(event.id) %>
      </h5>
      <small>
          <span class="badge badge-secondary"><%= event.is_reviewed ? 'vu' : 'à voir' %></span> |
          <span class="badge badge-secondary"><%= event.is_validated ? 'validé' : 'à valider' %></span>
      </small>
    </div>
    <div class="d-flex w-100 justify-content-between">
      <small class="mb-1">
        <%= event.start_date.strftime("%d/%m/%y") %></small>
      <small class="mb-1">
          <%= link_to "modifier", edit_admin_event_path(event.id) %> |
          <%= link_to "supprimer", admin_event_path(event.id), method: :delete %>
      </small>
    </div>
  </li>

app/views/admin/events/_form.html.erb
<div class="container">

    <%= simple_form_for @event do |f| %>

    <%= f.input :title %>

    <%= f.input :description %>

    <%= f.input :location %>

    <%= f.input :start_date %>

    <%= f.input :price %>

    <%= f.input :duration %>

    <%if @event.picture.attached? %>
    <%= image_tag @event.picture, alt: 'avatar' %>
    <%else%>
    <p>=== Il n'y a pas encore de pic lié à cet événement ===</p>
    <%end%>

    <%= f.input :picture, as: :file  %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="form-group row mb-0">
        <div class="col-sm-9 offset-sm-3">
            <%= f.button :submit, class: "btn-primary" %>
            <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
        </div>
    </div>
    <% end %>
</div>

app/views/admin/events/edit.html.erb
<h1>Modifier l'événement</h1>

<%= render 'form' %>

app/views/admin/events/index.html.erb
<div class="container">
    <h1>Events</h1>
    <h2>Look, you're an admin now!</h2>

  <div class="list-group">
    <%= render partial: 'event', collection: @events %>
  </div>

</div>

app/views/admin/events/show.html.erb
<div class="container">
    <div class="jumbotron">
        <h1><%= @event.title %></h1>
    </div>
    <div class="container">
        <h2>Status</h2>
        <p>Vu ? <%= @event.reviewed.to_s %></p>
        <p>Validé ? <%= @event.validated.to_s %></p>

    </div>
    </div>
    <h2>Utilisateur</h2>
    <p><%= @event.admin.email %></p>
    <p><a href="mailto:<%= @event.admin.email %>">Envoyer un mail</a></p>

    <h2>Description</h2>
    <p><%= @event.description %></p>

    <h2>Date</h2>
    <p><%= @event.start_date %></p>

    <h2>Lieu</h2>
    <p><%= @event.location %></p>

    <h2>Prix</h2>
    <p><%= @event.price %></p>
    
    <%if @event.picture.attached? %>
    <%= image_tag @event.picture, alt: 'avatar' %>
    <%else%>
    <p>=== Il n'y a pas encore de pic lié à cet événement ===</p>
    <%end%>
    
    <%= link_to "modifier", edit_admin_event_path(@event) %>
    <%= link_to "supprimer", admin_event_path(@event), method: :delete %>
</div>