config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendances
    resources :pictures, only: [:create, :update]
  end
  get 'events/:id/admin/', to: 'events#admin'
  resources :users do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :events
  end

  root 'events#index'
end

app/views/shared/_admin_navbar.html.erb
<class class="navbar navbar-expand-md bg-primary navbar-dark sticky-top">
    <a class="navbar-brand" href="/">EventMGMT</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb"
        aria-expanded="true">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to 'dashboard', admin_root_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
                <%= link_to 'users', admin_users_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
                <%= link_to 'events', admin_events_path, class: "nav-link" %>
            </li>
        </ul>

        <ul class="nav navbar-nav ml-auto">
            <!-- Dropdown AVEC user connected -->


            <li class="dropdown">
                <button class="dropdown-toggle btn btn-dark" id="dropdownMenuButton" data-toggle="dropdown" href="#"><span
                        class="fa fas fa-user"></span>
                    <%= user_signed_in? ? current_user.email : 'Log in' %>
                </button>
                <ul class="dropdown-menu dropdown-menu-right p-3" style="width: 250px;">
                    <li>
                        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    </li>
                    <li>
                        <%= link_to "edit_user_path", edit_user_path(current_user.id), class: "dropdown-item" %>
                    </li>
                    <li>
                        <%= link_to "Edit email / password", edit_user_registration_path, class: "dropdown-item" %>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</class>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
<div class="<%= flash_class(key) %> alert-dismissable fade show" role="alert">
  <%= value %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer justify-content-center py-3">
    <div class="container">
        <span class="text-muted"><a href="https://www.thehackingproject.org/dashboard/weeks/5/days/1?locale=fr">Made
                with some <i class="fa far fa-heart"></i></a></span>
        <div class="debug mb-3">
            <code>
                <%= debug(params) if Rails.env.development? %></code><br /><br />
        </div>
    </div>
</footer>
<div class="container">
</div>

app/views/shared/_navbar.html.erb
<class class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
    <a class="navbar-brand" href="/">EventMGMT</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb"
        aria-expanded="true">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%= link_to 'Home', root_path, class: "nav-link" %>
            </li>
        </ul>

        <ul class="nav navbar-nav ml-auto">
            <!-- Dropdown AVEC user connected -->
            <% if user_signed_in? %>
                <%= link_to 'Nouvel événement', new_event_path, class: "nav-item btn btn-primary", role: "button" %>
            <% end %>
            <li class="dropdown">
                <button class="dropdown-toggle btn btn-dark" id="dropdownMenuButton" data-toggle="dropdown" href="#"><span
                        class="fa fas fa-user"></span>
                        <%= user_signed_in? ? current_user.email : 'Log in' %>
                </button>
                <ul class="dropdown-menu dropdown-menu-right p-3" style="width: 250px;">
                    <!-- IF USER IS AUTHENTICATED -->
                    <% if user_signed_in? %>
                    <li>
                        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    </li>
                    <li>
                        <%= link_to "Edit profile", edit_user_path(current_user.id), class: "dropdown-item" %>
                    </li>
                    <li>
                        <%= link_to "Edit settings", edit_user_registration_path, class: "dropdown-item" %>
                    </li>   
                    <!-- IF USER IS NOT AUTHENTICATED -->
                    <% else %>
                    <li>
                        <%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %>
                    </li>
                    <li>
                        <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
                    </li>
                    <% end %>
                    <!-- IF USER IS ADMIN -->
                    <% if user_signed_in? && user_is_admin(current_user) %>
                    <li>
                    <%= link_to 'Dashboard', admin_root_path, class: "dropdown-item" %>
                    <% end %>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</class>