config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :attendances
    resources :pictures, only: [:create, :update]
  end
  get 'events/:id/admin/', to: 'events#admin'
  resources :users do
    resources :avatars, only: [:create]
  end

  namespace :admin do
    root 'admin#index'
    resources :users
    resources :events
  end

  root 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, inverse_of: 'admin'
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances
  has_one_attached :avatar
  
# REF 2019-02-17 Validation deactivated for heroku...
=begin
  validates :first_name,
          :last_name,
          :description,
          :email,
          :avatar, presence: true
=end
#  after_create :welcome_send

  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController


  def index
    puts "=" * 50
    puts "here's your index"
    puts User.all
    @users = User.all.sort_by { |k| k[:first_name] }
  end

  def show
    @user = User.find(params[:id])
    @events = Event.where(user_id: @user.id)
    attendances = Attendance.where(user_id: @user.id)
    @attended_events = attendances.map { |e| Event.find(e.event_id) }
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to request.referrer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @events = Event.where(user_id: params[:id])
    p @events
  end

  def edit
    if User.find(params[:id]) == current_user
      @user = current_user
    else
      flash[:warning] = "You're not #{User.find(params[:id]).first_name} !"
      redirect_to edit_user_path(current_user)
    end
  end

  def new

  end

  def create

  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Votre profil a été mis à jour !"
      redirect_to user_path @user
    else
      flash.now[:error] = "Problème, essayer encore !"
      render :new
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

end

private

def user_params
  params.require(:user).permit(:first_name, :last_name, :description, :avatar)
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user.html.erb
<li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
            <%= link_to user.full_name, admin_user_path(user.id) %>
        </h5>
        <span>
            (<%= user.id %>)</span>
    </div>

    <div class="d-flex w-100 justify-content-between">
        <%= user.email %>
        <small class="mb-1">
            <%= link_to "modifier", edit_admin_user_path(user.id) %> |
            <%= link_to "supprimer", admin_user_path(user.id), method: :delete %>
        </small>
    </div>
</li>

app/views/admin/users/edit.html.erb
<h2>Modifier le profil utilisateur</h2>


<%= simple_form_for @user do |f| %>

<%= f.input :first_name %>

<%= f.input :last_name %>

<%= f.input :description %>

<%if @user.avatar.attached? %>
<%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
<p>=== Il n'y a pas encore de pic lié à cet événement ===</p>
<%end%>

<%= f.input :avatar, as: :file %>

<div class="form-group row mb-0">
    <div class="col-sm-9 offset-sm-3">
        <%= f.button :submit, class: "btn-primary" %>
        <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    </div>
</div>
<% end %>

app/views/admin/users/index.html.erb
<% provide(:title, "Admin | Users") %>
<div class="container">
    <h1>Users</h1>
    <h2>Look, you're an admin now!</h2>

    <div class="list-group">
        <%= render partial: 'user', collection: @users %>
    </div>

</div>

app/views/admin/users/show.html.erb
<h1>User: <%= @user.email %></h1>

<%= @user.first_name %>
<%= @user.last_name %>

<h2>Activité</h2>

<h3>Événements proposés</h3>

<ul>
    <% @events.each do |event| %>
    <li><%= event.title %></li>
    <% end %>
</ul>

<h3>Participations</h3>

<ul>
    <% @attended_events.each do |attend| %>
        <li><%= attend.title %></li>
    <% end %>
</ul>